### ISSUE TITLE
Syntax error in redux example

### ISSUE THREAD

**Issue by chmac** [apollostack/react-docs#120]
Specifically I think this line under the "Using connect" heading is the issue:

    const List = function({ listId, onSelectList });

At first I thought it was some new wacky esN something that I hadn't seen before, but enabling all the transformations on [babel](https://babeljs.io/repl/) still throws an error.

I would have preferred to submit a PR to correct the error, but I can't actually figure out what it's supposed to be doing. As a general point of feedback, I'm new to graphql and apollo, but familiar with react & redux. I was unable to understand the whole "Using connect" part of the docs. I get the general idea, that connect() should be wrapped in the apollo bindings, or vice versa, but I can't figure out what that actually looks like from the example. Maybe an opportunity for a clearer example?

**Comment by stubailo** [comment]
Oh odd. That's supposed to be a basic React component. Don't know how it ended up being that syntax. Mind sending a PR to add a placeholder component there using the arrow function syntax?

**Comment by chmac** [comment]
Sure thing, will aim to do that when I get to a computer.

**Comment by stubailo** [comment]
Fixed by #124
