### ISSUE TITLE
Add a basic introduction to /tools

### ISSUE THREAD

**Issue by tmeasday** [apollostack/react-docs#37]
Here: https://github.com/apollostack/server-docs/blob/master/source/index.md

**Comment by tmeasday** [comment]
Do you want me to write up other issues on the repo?

**Comment by stubailo** [comment]
Yeah I'm not sure why this is on react-docs

**Comment by tmeasday** [comment]
I thought maybe it would be easier if all issues were on the one repo

**Comment by stubailo** [comment]
You can always look at https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Aapollostack+

But it's up to you.

**Comment by tmeasday** [comment]
Fair point

**Comment by tmeasday** [comment]
->https://github.com/apollostack/server-docs/issues/1
