### ISSUE TITLE
Document that __typename is not available by default in dataIdFromObject

### ISSUE THREAD

**Issue by HriBB** [apollostack/react-docs#47]
Docs state

> // If the IDs are only unique per type (this is typical if an ID is just an
// ID out of a database table), you can use the `__typename` field to scope it.
// This is a GraphQL field that's automatically available, but you do need
// to query for it also.
const client = new ApolloClient({
  dataIdFromObject: o => `${o.__typename}-${o.id},`
});

But I need to use `queryTransformer: addTypename` when constructing `new ApolloClient˙ for `__typename` to be available.

```
import ApolloClient, { addTypename } from 'apollo-client';

const client = new ApolloClient({
  dataIdFromObject: o => `${o.__typename}-${o.id},`
  queryTransformer: addTypename,
});
```

**Comment by stubailo** [comment]
Should we just make the typename transform be on by default? I feel like almost everyone uses it.

**Comment by HriBB** [comment]
Probably. At least mention it in the docs. I had to ask on a slack chat to get the answer

**Comment by helfer** [comment]
This will no longer be true in 0.5
