### ISSUE TITLE
Make it clear you can add multiple queries or mutations per component by adding multiple containers

### ISSUE THREAD

**Issue by stubailo** [apollostack/react-docs#56]

**Comment by Siyfion** [comment]
Especially as the docs seem to suggest that when you wrap a mutation you pass a `mutate` prop to the wrapped component, but if you have two mutations they clearly can't both be called `mutate`. I would assume that much in the same way a query can utilise a function that changes the props passed: `props: ({ ownProps, data }) => {}` that you could do the same/similar with a mutation in order to give them unique names?

**Comment by GreenAsJade** [comment]
I thought I cleared this up with my recent addition here:

http://dev.apollodata.com/react/mutations.html#basics

which says:

If you need more than one mutation on a component, you make a graphql container for each:

```
const NewEntryWithData =  graphql(submitNewUser, {name : 'newUserMutation'})(
  graphql(submitRepository, {name: 'newRepositoryMutation'})(Component)
)
```
Note the use of the name option on the graphql() call to name the prop that will receive the mutation function for each mutation (by defaut that name is ‘mutate)

**Comment by Siyfion** [comment]
Ah sorry @GreenAsJade I hadn't spotted that addition! Yes, that does clear it all up perfectly, thanks! 👍

**Comment by stubailo** [comment]
@rdickert I heard this is something you had a nice solution for.

**Comment by kachkaev** [comment]
I also felt a bit confused when got a need to have multiple mutations per component using Apollo. My gut feeling suggests that a large stack of HOC is not expensive, but this does not look 100% intuitive. Besides, I don't quite like how this structure looks:

```js
export default withData(
  withMutationA(
    withMutationB(
      WithMutationC(
        MyComponent
      )
    )
  )
);
```

Each time I add or  remove a mutation I have to commit at least two rows here. If I want to keep the correct indents, the number of rows to commits becomes `2N+1`.

Maybe there exists be something like this?
```js
export default russianDoll(
  withData,
  withMutationA,
  withMutationB,
  withMutationC,
  MyComponent
)
```

The name of the function is just an association with [_Matryoshka_](https://en.wikipedia.org/wiki/Matryoshka_doll) :–)

Would be good to have a short comment on handling such situation in the docs. This feels missing.

**Comment by GreenAsJade** [comment]
@kachkaev http://dev.apollodata.com/react/higher-order-components.html#compose

**Comment by rdickert** [comment]
@GreenAsJade that looks great. I also just wrote a blog post about this – I think that [HOCs that place a single prop on your component are great for composition](https://www.okgrow.com/posts/compose-react-sphoc)., and as you pointed out, it works for more than just GraphQL operations.

**Comment by helfer** [comment]
Looks like this is settled then?

**Comment by sheprdinc** [comment]
@GreenAsJade your explanation on Oct 21, 2016, worked beautifully, but this example only illustrates how to join/chain mutations together... i typically create a single component that can dynamically handle both CREATE and UPDATE operations (this is becoming more and more common), which means I'm needing to combine or chain together both QUERIES and MUTATIONS into the graphql() call... can you pls provide an example of this? (i am not having much luck)

**Comment by merges** [comment]
I know this issue is closed, but just another +1 for examples in the documentation that show *multiple* queries and *multiple* mutations, rather than just 1 of each.

**Comment by stubailo** [comment]
We have one here: http://dev.apollodata.com/react/mutations.html#multiple-mutations

Happy to accept PRs where appropriate to add more!

**Comment by naisergic-qss** [comment]
export default compose(
  graphql(query, queryOptions),
  graphql(query, queryOptions),
  graphql(query, queryOptions),
)(Component);
if I will Combine my queries in the above mentioned format, then I will get the result of only one query in props.data, componentWillReceiveProps is called every time when another request gets completed but I am not able to get result of other queries. Any suggestion on this

**Comment by naisergic-qss** [comment]
I found the answer just posting here if in future someone look for it.
We have to create aliases for each query like
const Listt = graphql(Query,{
    options : {
        variables: {
            filters:filter
        }
    }
,name:'your Aliase'})
