### ISSUE TITLE
Possible wrong information on redux integration

### ISSUE THREAD

**Issue by drFabio** [apollostack/react-docs#74]
I tried to follow [this](http://dev.apollodata.com/react/redux.html) I was receiving:

> Cannot read property 'getState' of undefined
I had to do this 
```javascript
const reducer = return combineReducers({
    apollo: client.reducer()
  })
const createStoreWithMiddleware = applyMiddleware(client.middleware())(applyMiddleware(thunk)(createStore))
const store = createStoreWithMiddleware(reducer))
```
Should the middleware use be required ?Is the doc wrong , the implementation wrong or more probable  I am doing something wrong?

**Comment by stubailo** [comment]
Just saw this PR: https://github.com/apollostack/react-docs/pull/72

Perhaps with the new docs it is correct now?

**Comment by drFabio** [comment]
Wow that was quick. Yes I guess so will close it then
