### ISSUE TITLE
Examples for multiple queries and mutators and custom scalar types

### ISSUE THREAD

**Issue by janikvonrotz** [apollostack/react-docs#80]
Hey there,

Heard you would love to get some feedback.
I would have loved to see minimal example of multiple queries and mutators. Something like this:

```
...
const updateMutation = gql`
mutation updateCategory($id: String, $label: String) {
  updateCategory(id: $id, label: $label)
}
`;
const deleteMutation = gql`
mutation deleteCategory($id: String) {
  deleteCategory(id: $id)
}
`;
const CategoryEditWithMutation = graphql(updateMutation, {
  props({ mutate }) {
    return {
      updateCategory({id, label}) {
        return mutate({ variables: { id, label }});
      }
    };
  },
})(graphql(deleteMutation, {
  props({ mutate }) {
    return {
      deleteCategory(id){
        return mutate({ variables: { id }});
      }
    };
  },
})(CategoryEdit));
 
const query = gql`
query getCategory($id: String) {
  category(id: $id) {
    id
    label
  }
}
`;
const CategoryEditWithData = graphql(query, {
  options: (ownProps) => ({ variables: { id: ownProps.params.id } }),
})(CategoryEditWithMutation);
 
export default CategoryEditWithData;
...
```

another problem I've solved for my case was the definition of an custom scalar type. My example:

**schema.js**

```
scalar Date
...
type Category {
  id: String
  label: String
  createdAt: Date
}
...
```

Define a new scalar, which is basically another type.

**resolvers.js**

```
  Date: {
    __parseValue(value) {
      return new Date(value); // value from the client
    },
    __serialize(value) {
      return value.toISOString(); // value sent to the client
    },
    __parseLiteral(ast) {
      return ast.value;
    },
  },
```

Please let me know what you think of those ideas.

**Comment by helfer** [comment]
@janikvonrotz thanks for the feedback! If it's not already documented, we should show how to combine multiple queries/mutations with `compose` (and maybe mention that one can also stack components like you did).

For the custom scalars, have you seen this? http://dev.apollodata.com/tools/graphql-tools/scalars.html

**Comment by janikvonrotz** [comment]
@helfer Yes I could make a PR.
Is my example sufficient? 
Should I translate my example into your repository schema?
And in which chapter would like to see this kind of example?
=> It would be a mix of Usage / Queries and Usage / Mutations or should I seperate them?
=> I personally would have put it into the Mutations chapter.

thanks for your feedback.

**Comment by helfer** [comment]
@janikvonrotz Awesome, thanks!

I think it would be better to make an example with connect. I think it's fine to just put an example at the bottom of the mutations page that shows how to make a component that has one query and one mutation. I assume people will be able to extrapolate from that.

**Comment by helfer** [comment]
Is this issue the same as #56?

**Comment by stubailo** [comment]
Yes!
